### ISSUE TITLE
Body (Input) is not updated

### ISSUE THREAD

**Issue by michaelrommel** [gchaincl/httplab#17] opened 2017-03-06 12:49 UTC
Hi,

maybe I am missing something very obvious, but for me the Editor field for "Body (Input)" is not working.

Changes, which I make to the Status, Delay or Header Fields take effect.
When I load a predefined Reponse body from the .httplab file, the changes take effect.
But when I enter a Response Body by hand in the editor field, the body returned does not reflect the change (regardless, whether I stay in the Editor, change to another input field, use Ctrl-A for updating the response or not)

Any ideas, why this happens? I have tried to locate the issue, but since I do not know go, it is quite hard.

**Comment by gchaincl** [comment] 2017-03-06 12:52
I'll try to reproduce and verify what's wrong, for now, would mind to elaborate a list of steps to reproduce it, or provide an ascii animation?
Thanks for the feedback!

**Comment by gchaincl** [comment] 2017-03-06 12:53
Yep, you're right, looks like a bug introduced after the Body Field.

**Comment by gchaincl** [comment] 2017-03-06 13:02
@michaelrommel it should be fixed now, please verify and confirm

**Closed** 2017-03-06 13:02 UTC
Labels: bug

**Comment by michaelrommel** [comment] 2017-03-06 14:36
Hi, yes, I can confirm that this works now! Thanks for the quick fix!

**Comment by gchaincl** [comment] 2017-03-06 15:55
Cool, thanks for the issue!
